# Generated by Django 4.1 on 2024-01-18 23:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("feed", "0002_rename_relqted_post_comment_related_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="pub_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="pub_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
    ]
