# Generated by Django 4.1 on 2024-02-06 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("feed", "0003_alter_comment_replyto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="replyto",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="feed.comment",
            ),
        ),
    ]
